- name: Install PostgreSQL and Odoo on Remote Server
  hosts: remote_server
  become: true
  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
        update_cache: yes
        
    - name: Start PostgreSQL Service
      service:
        name: postgresql
        state: started
        enabled: yes
        use: sysvinit

    - name: Install gpg
      apt:
        name: gpg
        state: present

    - name: Download Odoo GPG Key
      shell: |
        wget -qO- https://nightly.odoo.com/odoo.key | gpg --dearmor | tee /usr/share/keyrings/odoo-archive-keyring.gpg > /dev/null

    - name: Add Odoo Repository with Proper Keyring
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/odoo.list
        content: |
          deb [signed-by=/usr/share/keyrings/odoo-archive-keyring.gpg] https://nightly.odoo.com/18.0/nightly/deb/ ./
        mode: '0644'

    - name: Install Odoo
      apt:
        name: odoo
        state: present
        update_cache: yes

    - name: Start Odoo Service
      service:
        name: odoo
        state: started
        enabled: yes
        use: sysvinit
